### ISSUE TITLE
V2版本删除指令不执行

### ISSUE THREAD

**Issue by xiaojiuawa** [BalloonUpdate/McPatch2#1]
## 错误详情
使用V2版本管理端创建更新包，里面只要有任意文件的删除，客户端都不会执行，客户端执行更新后，文件还是存在，并未删除

## 使用版本
- 管理/服务端：V2 0.0.5
- 客户端：V2 0.0.8
- 加载器：loader-2

**Comment by asforest** [comment]
已在客户端[0.0.9版本](https://github.com/BalloonUpdate/McPatch2/releases/tag/c0.0.9)中修复。如有新的问题出现，请重新开启。
