### ISSUE TITLE
webdav问题

### ISSUE THREAD

**Issue by DSLZL** [BalloonUpdate/McPatch2#10]
按照配置文件的设置
使用了webdavs
但是会显示url无效或者检测不到此url（忘了是什么）
删除s，变为webdav则能用

**Comment by asforest** [comment]
烦请提供一下具体的错误截图或者详细报错日志

**Comment by DSLZL** [comment]
![55BB076D871B189700C6C6643C8FD6EE](https://github.com/user-attachments/assets/a2543f51-b51d-4d1c-8b5c-92c561c3932f)

**Comment by asforest** [comment]
已修复 https://github.com/BalloonUpdate/McPatch2/releases/tag/c0.0.15
