### ISSUE TITLE
服务端自动升级

### ISSUE THREAD

**Issue by DSLZL** [BalloonUpdate/McPatch2#11]
可以么？

**Comment by asforest** [comment]
服务端十分不建议自动升级。在没有充分阅读新版本新记录前提下，贸然升级可能会导致严重后果。

服务端只能手动升级。

**Comment by DSLZL** [comment]
> 服务端十分不建议自动升级。在没有充分阅读新版本新记录前提下，贸然升级可能会导致严重后果。
> 
> 服务端只能手动升级。

我觉得可有更新公告
