### ISSUE TITLE
历史更新日志

### ISSUE THREAD

**Issue by DSLZL** [BalloonUpdate/McPatch2#18]
添加一个功能能让玩家就算没有更新也能看到以前的更新日志

**Comment by asforest** [comment]
更新日志需要从服务端拉取。检查是否有更新也需要从服务端拉取。
这两个请求发出去后到达客户端的时间差不会相隔太多，当判断没有更新时，应该尽快结束运行，避免拉住mc启动进程，而不是显示之前的更新记录。
总体感觉意义不大

**Comment by DSLZL** [comment]
> 更新日志需要从服务端拉取。检查是否有更新也需要从服务端拉取。
> 这两个请求发出去后到达客户端的时间差不会相隔太多，当判断没有更新时，应该尽快结束运行，避免拉住mc启动进程，而不是显示之前的更新记录。
> 总体感觉意义不大

可以加一个设置用户选择看不看？

**Comment by asforest** [comment]
这个功能用的人太少，时间成本比收益高，所以暂时不会做。
