### ISSUE TITLE
png文件更新问题

### ISSUE THREAD

**Issue by yumo135** [BalloonUpdate/McPatch2#27]
无法将png文件更新到客户端

**Comment by yumo135** [comment]
![屏幕截图 2024-09-25 000224](https://github.com/user-attachments/assets/22abdd23-38ab-4e3b-b2e8-1bedac66abf4)
已尝试所有png文件，进度条卡住不动

**Comment by yumo135** [comment]
[mcpatch.log](https://github.com/user-attachments/files/17117944/mcpatch.log)
以上为日志
![image](https://github.com/user-attachments/assets/ad79f8a5-3778-4169-9126-60cb526c5a8f)
似乎在文件量多的情况下掺杂png文件会触发，卡住进度条

**Comment by asforest** [comment]
方便的话，可以提供一份public文件夹压缩包吗

**Comment by yumo135** [comment]
好的，问题出现在0.1.0的public

**Comment by yumo135** [comment]
好的，问题出现在0.1.0的public
但是压缩体积很大，有300多m，已用123发送
https://www.123865.com/s/UUgKVv-4UJJA

**Comment by asforest** [comment]
本地跑过测试，没有复现png文件卡住的问题。您这边能排除是网络原因引起的吗？

**Comment by yumo135** [comment]
现在测试时又可以正常更新了，也许就是网络问题

**Comment by asforest** [comment]
嗯。我并没有针对png格式文件做任何特殊处理，所有后缀名的文件都是一视同仁的，不太可能会单独卡在png这里。

不过到时有人反馈过，服务端使用时间长了，可能会卡住，需要重启。这个问题目前还没有修复，可以注意一下。

**Comment by yumo135** [comment]
好的，麻烦了

**Comment by asforest** [comment]
先关闭此issue了。如果遇到新的问题，请重新开启。
