### ISSUE TITLE
不支持带空格的路径

### ISSUE THREAD

**Issue by Cnzw** [BalloonUpdate/McPatch2#4]
![image](https://github.com/BalloonUpdate/McPatchManage/assets/20514522/8f3fee3a-2096-42c3-9a2d-1c77e498a362)

**Comment by asforest** [comment]
856d62814451b04272772dfa2d1b508e4e9d3327

**Comment by 0XPYEX0** [comment]
要不要加双引号框起来试试()

**Comment by Cnzw** [comment]
> 要不要加双引号框起来试试()

文件是通过双击exe运行的，并不是通过命令行调用的。

该问题已被作者确认为BUG，[已经修复](https://github.com/BalloonUpdate/McPatch2/releases/tag/m0.0.6)。
